### ISSUE TITLE
Bludit 3.10.0 duplicate directories in the bl-plugins dir

### ISSUE THREAD

**Issue by mhancoc7** [bludit/bludit#1103]
### Describe your problem
duplicate directories in the bl-plugins dir

### Steps to reproduce the problem
Extract the zip and open bl-plugins

### Bludit version
3.10.0 PRO

![image](https://user-images.githubusercontent.com/1692414/67642748-e6316080-f8dc-11e9-9787-48aaa0fc6c20.png)

**Comment by dignajar** [comment]
I just fixed it, it looks like the Japanese language was in the wrong place.

**Comment by mhancoc7** [comment]
> I just fixed it, it looks like the Japanese language was in the wrong place.

Thanks man! I assume the download zips for Bludit and Bludit PRO will be updated? I just checked and they still have the duplicate directories. Figured you just haven't updated the zips yet.

Thanks!!

**Comment by dignajar** [comment]
Next release, I need to finish with some bug fixes then I going to release the version 3.10.1

**Comment by mhancoc7** [comment]
Sounds great. Thanks
