### ISSUE TITLE
Misbehaviour child pages

### ISSUE THREAD

**Issue by DMTGMBH** [bludit/bludit#1380]
### Describe your problem
Parent pages are not stored correctly. (Re)Assigning parent pages causes troubles. 

### Steps to reproduce the problem
Create a page, select a parent page and save it. After editing again the parent page is removed by the system. After selecting the parent page again and leaving everything untouched, it is not saved. Only this workaround for reassigning parent pages leads to the expected result: edit the page, select the parent page, save it, select the parent page again, save it again will produce the expected result.

### Bludit version
4.0.0 beta 2 > latest from github

### PHP version
7.4-latest FP

Here you can check the misbehaviour:
https://user-images.githubusercontent.com/4006288/139573293-baaf16df-4773-48c1-886c-0b0b2b9745f8.mp4

**Comment by Torsten-K** [comment]
I can confirm this misbehaviour. The workaround does the trick, but in the page list, the child page is not indented as it used to be in Bludit 3.

**Comment by dignajar** [comment]
Fixed

**Comment by Torsten-K** [comment]
This still does not work flawlessly. Sometimes a child page is correctly assigned to a parent page and saved accordingly, sometimes not. There seems to be something wrong with the saving process in certain cases. Unfortunately, I can't see any pattern of misbehaviour.

**Comment by Torsten-K** [comment]
Same issue on Bludit 4.0.0 RC2. Not even editing an existing static page is possible, no matter if PHP 7.4 or 8.1 is running on Apache HTTP server
![error-trying-to-edit-the-page](https://user-images.githubusercontent.com/806012/161385517-b911ba33-1f7f-42f9-b21b-7902d148d4e1.jpg)
.

**Comment by clickwork-git** [comment]
The same is the case if a child page is opened for editing (but is not edited) and the button "Saved" is clicked.

**Comment by emanueleg** [comment]
Does the issue still exist in 4.0.0-rc-3?

**Comment by clickwork-git** [comment]
> Does the issue still exist in 4.0.0-rc-3?

Not yet.

**Comment by clickwork-git** [comment]
> Does the issue still exist in 4.0.0-rc-3?

It works for static content, not default content.

**Comment by Torsten-K** [comment]
In 4.0.0-rc-3 I haven’t yet encountered this error.
